### ISSUE TITLE
constrained spreadsheet autocomplete width

### ISSUE THREAD

**Issue by kinghat** [obelisk79/OpenDark#44]
you can see that the width of the autocomplete box is constrained in its width:

![image](https://github.com/obelisk79/OpenDark/assets/16073360/5a0e6548-10a0-469b-851e-f5ae679f7446)

**Comment by obelisk79** [comment]
@kinghat I was doing some testing for this, and it appears that this happens with all themes. The width of the listview here seems to be tied to the cell-width. I'm not sure if this is a Qt issue or a FreeCAD's implementation issue, but I doubt that I can resolve this within the OpenTheme framework I've created.

I'll leave this open for now because I still have a few things I'd like to try.

**Comment by obelisk79** [comment]
I found a way to change the minimum width. I just need to be mindful for unintended changes elsewhere as a result
![image](https://github.com/obelisk79/OpenDark/assets/17993710/47b6ce0b-dcab-4df3-887b-4bff6ca88a33)

**Comment by obelisk79** [comment]
Ok, I think this should now be resolved, hopefully I'll have an update pushed out soon.
