### ISSUE TITLE
Sketcher: Mouse coordinates/dimensions hard to read

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#49]
When moving geometry or placing new ones (e.g. with the polyline tool) the coordinates / dimensions are displayed next to the mouse cursor. The text is really small and the blue is hard to read when using the dark theme:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/43a288af-9c69-43a0-8d77-ada83f85119b)
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/2d53c562-d6c6-4b3b-85a6-8a3377778b28)

**Comment by hasecilu** [comment]
I think it was already updated because I see the text white.

But now there is another problem: the lines are white and the text is white, if both overlap the text is no readable. Maybe adding a dark transparent background behind the text label will force a better contrast.

![image](https://github.com/obelisk79/OpenDark/assets/53124818/b06d9a4d-6f6b-4aa6-807e-0f447ac428ec)

**Comment by maxwxyz** [comment]
Text is white now. I'm ok with that. A darker background so close to the cursor would be more annoying for me as even more geometry would be hidden.
Maybe when the on view parameters are implemented in all tools, this overlay could be removed in general.
![image](https://github.com/obelisk79/OpenDark/assets/6246609/070d16b1-bf5d-4d24-bf12-e96cda9d32a3)
